version: '3'
services:
    postgres:
        image: postgres
        env_file: .env
        volumes:
            - ~/data/publitas/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    mongo:
        image: mongo
        env_file: .env
        ports:
            - "27017:27017"
        volumes:
            - ~/data/publitas/mongodb:/data/db

    mongo-express:
        image: mongo-express
        env_file: .env
        ports:
            - "8081:8081"
        links:
            - mongo
