version: '2.1'
services:
    postgres:
        image: postgres
        env_file: .env
        volumes:
            - ~/data/postgresql/publitas/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 60s
            timeout: 5s
            retries: 3
